nohup: 忽略输入
 * Serving Flask app 'github'
 * Debug mode: on
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8801
 * Running on http://172.26.23.117:8801
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 469-473-216
INFO:werkzeug:47.92.79.156 - - [15/May/2023 12:57:22] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.37.1 - - [15/May/2023 12:57:22] "GET http://39.100.66.203/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.30.214 - - [15/May/2023 12:57:22] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
ERROR:werkzeug:89.248.165.106 - - [15/May/2023 14:45:04] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x02\x00\x00\x00')
INFO:werkzeug:89.248.165.106 - - [15/May/2023 14:45:04] "[35m[1m\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x02\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
remote: Resolving deltas:   0% (0/4)        remote: Resolving deltas:  25% (1/4)        remote: Resolving deltas:  50% (2/4)        remote: Resolving deltas:  75% (3/4)        remote: Resolving deltas: 100% (4/4)        remote: Resolving deltas: 100% (4/4), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   b30e77b..20196b1  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[8:00:00], next run at: 2023-05-16 04:02:35 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 21, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 20196b1ab619b2f0c091d03994936d26afd379fb but expected b30e77b31a6fef01b5ff196dfc70b790a714834d)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[8:00:00], next run at: 2023-05-16 04:02:36 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 21, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/4)        remote: Resolving deltas:  25% (1/4)        remote: Resolving deltas:  50% (2/4)        remote: Resolving deltas:  75% (3/4)        remote: Resolving deltas: 100% (4/4)        remote: Resolving deltas: 100% (4/4), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   20196b1..645c24b  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[8:00:00], next run at: 2023-05-16 12:02:35 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 21, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/6)        remote: Resolving deltas:  16% (1/6)        remote: Resolving deltas:  33% (2/6)        remote: Resolving deltas:  50% (3/6)        remote: Resolving deltas:  66% (4/6)        remote: Resolving deltas:  83% (5/6)        remote: Resolving deltas: 100% (6/6)        remote: Resolving deltas: 100% (6/6), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 645c24b921783842c2c19fd132fd9627bd07cda6 but expected 20196b1ab619b2f0c091d03994936d26afd379fb)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[8:00:00], next run at: 2023-05-16 12:02:36 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 21, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:35.203.211.12 - - [16/May/2023 07:04:40] "GET / HTTP/1.1" 200 -
INFO:werkzeug:47.92.67.105 - - [16/May/2023 09:00:59] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
INFO:werkzeug:8.142.87.162 - - [16/May/2023 09:00:59] "GET http://39.100.66.203/ HTTP/1.1" 200 -
INFO:werkzeug:8.142.42.74 - - [16/May/2023 09:00:59] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   645c24b..db334ed  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[8:00:00], next run at: 2023-05-16 20:02:35 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 21, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at db334edec198ab67535f523f55d8dbbf2733d133 but expected 645c24b921783842c2c19fd132fd9627bd07cda6)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[8:00:00], next run at: 2023-05-16 20:02:36 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 21, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:werkzeug:152.89.196.122 - - [16/May/2023 12:37:03] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
INFO:werkzeug:152.89.196.122 - - [16/May/2023 12:37:03] "[35m[1m\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
INFO:werkzeug:1.202.165.115 - - [16/May/2023 17:51:04] "[33mGET /github/contribute HTTP/1.1[0m" 404 -
running...
[main 20196b1] 2023年 05月 15日 星期一 20:02:35 CST
 3 files changed, 2 insertions(+), 1 deletion(-)
 rewrite log.txt (87%)
running...
[main 645c24b] 2023年 05月 16日 星期二 04:02:35 CST
 2 files changed, 42 insertions(+)
running...
[main db334ed] 2023年 05月 16日 星期二 12:02:36 CST
 2 files changed, 46 insertions(+)
