nohup: 忽略输入
 * Serving Flask app 'github'
 * Debug mode: on
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8801
 * Running on http://172.26.23.117:8801
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 469-473-216
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
remote: Resolving deltas:   0% (0/4)        remote: Resolving deltas:  25% (1/4)        remote: Resolving deltas:  50% (2/4)        remote: Resolving deltas:  75% (3/4)        remote: Resolving deltas: 100% (4/4)        remote: Resolving deltas: 100% (4/4), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   dc3b1d2..37c7598  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 04:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 37c7598143a24f77cee8e9c3cbc03c1e0bf2a3b3 but expected dc3b1d24bde621b3915671440bf9f9ac0993e03a)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 04:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/6)        remote: Resolving deltas:  16% (1/6)        remote: Resolving deltas:  33% (2/6)        remote: Resolving deltas:  50% (3/6)        remote: Resolving deltas:  66% (4/6)        remote: Resolving deltas:  83% (5/6)        remote: Resolving deltas: 100% (6/6)        remote: Resolving deltas: 100% (6/6), completed with 2 local objects.        
remote: Resolving deltas:   0% (0/4)        remote: Resolving deltas:  25% (1/4)        remote: Resolving deltas:  50% (2/4)        remote: Resolving deltas:  75% (3/4)        remote: Resolving deltas: 100% (4/4)        remote: Resolving deltas: 100% (4/4), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at e303c818cb4c8f81a82c6ff911d254d31739e8a8 but expected 37c7598143a24f77cee8e9c3cbc03c1e0bf2a3b3)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 09:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   37c7598..e303c81  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 09:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:162.216.149.131 - - [20/May/2023 07:37:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug:47.92.30.57 - - [20/May/2023 08:58:40] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.72.15 - - [20/May/2023 08:58:40] "GET http://39.100.66.203/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.79.86 - - [20/May/2023 08:58:40] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
remote: Resolving deltas:   0% (0/4)        remote: Resolving deltas:  25% (1/4)        remote: Resolving deltas:  50% (2/4)        remote: Resolving deltas:  75% (3/4)        remote: Resolving deltas: 100% (4/4)        remote: Resolving deltas: 100% (4/4), completed with 2 local objects.        
remote: Resolving deltas:   0% (0/6)        remote: Resolving deltas:  16% (1/6)        remote: Resolving deltas:  33% (2/6)        remote: Resolving deltas:  50% (3/6)        remote: Resolving deltas:  66% (4/6)        remote: Resolving deltas:  83% (5/6)        remote: Resolving deltas: 100% (6/6)        remote: Resolving deltas: 100% (6/6), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   e303c81..24bf0f0  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 14:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 24bf0f0f8f6a704781461540011bd1c08ba02f3d but expected e303c818cb4c8f81a82c6ff911d254d31739e8a8)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 14:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   24bf0f0..7bbc467  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 19:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   7bbc467..1f24191  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-20 19:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   1f24191..19c804f  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 00:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   19c804f..c47c3a4  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 00:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   c47c3a4..5e6e05d  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 05:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 5e6e05d04223d10e0be48e03059c06d0648d4027 but expected c47c3a404f515001caba910e2316f02b064fbcc4)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 05:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:werkzeug:152.89.196.122 - - [21/May/2023 02:40:28] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
INFO:werkzeug:152.89.196.122 - - [21/May/2023 02:40:28] "[35m[1m\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at adfe65fed143eedfe07a629faa4a19ede48629a6 but expected 5e6e05d04223d10e0be48e03059c06d0648d4027)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 10:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   5e6e05d..adfe65f  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 10:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:162.216.149.94 - - [21/May/2023 08:24:04] "GET / HTTP/1.1" 200 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at ee9f236dd7cce59c944e1a8f815417afb8ded966 but expected adfe65fed143eedfe07a629faa4a19ede48629a6)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 15:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   adfe65f..ee9f236  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 15:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:werkzeug:87.251.64.11 - - [21/May/2023 13:39:41] code 400, message Bad request version ('È')
INFO:werkzeug:87.251.64.11 - - [21/May/2023 13:39:41] "[35m[1m\x12\x01\x00^\x00\x00\x01\x00\x00\x00$\x00\x06\x01\x00*\x00\x01\x02\x00+\x00\x01\x03\x00,\x00\x04\x04\x000\x00\x01\x05\x001\x00$\x06\x00U\x00\x01ÿ\x04\x07\x0c¼\x00\x00\x00\x00\x00\x00\x15Ð\x00 \x00\x00\x00\x00\x00\x00\x00À\x0cÈ[0m" HTTPStatus.BAD_REQUEST -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   ee9f236..2a3c186  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 20:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   2a3c186..82e1ce9  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-21 20:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   82e1ce9..a608cab  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 01:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at a608cab9b16135b42e637394909e0098183b0fad but expected 82e1ce90730a86ce92c1e330656ca5d4774c62c9)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 01:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   a608cab..efdfd5b  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 06:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   efdfd5b..8165004  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 06:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at d5d97e94991cb7be36e2e35a71d54af11cfe3ec8 but expected 81650040734bc2f3b497df141507bc9253d6e6ad)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 11:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   8165004..d5d97e9  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 11:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:162.216.150.225 - - [22/May/2023 08:57:18] "GET / HTTP/1.1" 200 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 53287f805c7b22e268114d164be1954c513f9d7f but expected d5d97e94991cb7be36e2e35a71d54af11cfe3ec8)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 16:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   d5d97e9..53287f8  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 16:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 4d17742e1015aff129d2b640032c57b63b93ff10 but expected 53287f805c7b22e268114d164be1954c513f9d7f)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 21:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   53287f8..4d17742  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-22 21:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   4d17742..6d6da81  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 02:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 6d6da81df354cfea8b66370743641a2fd5be354e but expected 4d17742e1015aff129d2b640032c57b63b93ff10)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 02:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 4cc1ca647d8eb0648d0b14a6fd228845f2221c4f but expected 6d6da81df354cfea8b66370743641a2fd5be354e)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 07:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   6d6da81..4cc1ca6  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 07:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:35.203.211.123 - - [23/May/2023 03:34:43] "GET / HTTP/1.1" 200 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 8818ec954f44c685d80d7c0831c2449a6a7ed796 but expected 4cc1ca647d8eb0648d0b14a6fd228845f2221c4f)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 12:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   4cc1ca6..8818ec9  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 12:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at cb02ffc320db25ddf33ee19a25c8d1f25066d1b3 but expected 8818ec954f44c685d80d7c0831c2449a6a7ed796)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 17:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   8818ec9..cb02ffc  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 17:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   cb02ffc..0dd6e6d  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 22:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   0dd6e6d..d46564b  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-23 22:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:werkzeug:92.63.196.148 - - [23/May/2023 21:09:00] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
INFO:werkzeug:92.63.196.148 - - [23/May/2023 21:09:00] "[35m[1m\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   d46564b..67b5c48  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 03:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 67b5c48f3554fd47b34bd5327db2ba2a42776646 but expected d46564ba9a1c203aff665a5f2d7d8643b1fe098b)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 03:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 80d983c6e11450ae4c26c36a1c40cc119252f3da but expected 67b5c48f3554fd47b34bd5327db2ba2a42776646)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 08:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   67b5c48..80d983c  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 08:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:35.203.211.161 - - [24/May/2023 04:15:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:47.92.31.143 - - [24/May/2023 05:55:28] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.79.156 - - [24/May/2023 05:55:28] "GET http://39.100.66.203/ HTTP/1.1" 200 -
INFO:werkzeug:8.142.104.65 - - [24/May/2023 05:55:28] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   80d983c..6b26a0f  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 13:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/2)        remote: Resolving deltas:  50% (1/2)        remote: Resolving deltas: 100% (2/2)        remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To github.com:ashen-23/ashen_boring.git
   6b26a0f..cdb579a  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 13:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:werkzeug:161.189.42.18 - - [24/May/2023 11:43:28] code 400, message Bad request syntax ('333766643833656338616434363333643963363962386536653538383937393235613033653338636434')
INFO:werkzeug:161.189.42.18 - - [24/May/2023 11:43:28] "[35m[1m333766643833656338616434363333643963363962386536653538383937393235613033653338636434[0m" HTTPStatus.BAD_REQUEST -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 00dea89e28ac7be0e19aa3b056eaefed46899287 but expected cdb579ac17207d6692099ab5866c29d0da63d984)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 18:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   cdb579a..00dea89  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 18:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/3)        remote: Resolving deltas:  33% (1/3)        remote: Resolving deltas:  66% (2/3)        remote: Resolving deltas: 100% (3/3)        remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   00dea89..4ca8a93  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 23:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 4ca8a93e51812ca3f4b8d97988712d0753e9952c but expected 00dea89e28ac7be0e19aa3b056eaefed46899287)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-24 23:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
   4ca8a93..c03b009  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-25 04:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at c03b009a0a67d4918111785448e3e1874dbcbeae but expected 4ca8a93e51812ca3f4b8d97988712d0753e9952c)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-25 04:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:35.203.211.155 - - [25/May/2023 01:50:36] "GET / HTTP/1.1" 200 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at b76aa56e6613b82b45f919b307ef87a054c7af74 but expected c03b009a0a67d4918111785448e3e1874dbcbeae)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-25 09:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   c03b009..b76aa56  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-25 09:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR:werkzeug:111.7.96.147 - - [25/May/2023 08:12:07] code 400, message Bad request version ('À\x13À')
INFO:werkzeug:111.7.96.147 - - [25/May/2023 08:12:07] "[35m[1m\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03I\x06²ù¼\x99iÀYûøºe-\x83Ud]\x0e\x8d·b8´gÆÝ9dZ8f gÁ\x81i³öòË°©\x19NÖ½\x95g|püé<Z¡\x90T·é¥8'O;\x00&À+À/À,À0Ì©Ì¨À\x09À\x13À[0m" HTTPStatus.BAD_REQUEST -
INFO:werkzeug:111.7.96.147 - - [25/May/2023 08:12:17] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.99.191 - - [25/May/2023 08:15:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.99.191 - - [25/May/2023 08:15:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:106.225.211.177 - - [25/May/2023 08:16:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:106.225.211.177 - - [25/May/2023 08:16:02] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:175.6.125.133 - - [25/May/2023 08:16:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.125.133 - - [25/May/2023 08:16:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:106.227.33.134 - - [25/May/2023 08:16:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:106.227.33.134 - - [25/May/2023 08:16:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:175.6.77.12 - - [25/May/2023 08:16:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.77.12 - - [25/May/2023 08:16:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:175.6.143.32 - - [25/May/2023 08:16:37] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.143.32 - - [25/May/2023 08:16:38] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:125.124.60.119 - - [25/May/2023 08:16:40] "GET / HTTP/1.1" 200 -
INFO:werkzeug:125.124.60.119 - - [25/May/2023 08:16:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:125.124.7.0 - - [25/May/2023 08:16:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:125.124.7.0 - - [25/May/2023 08:16:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:106.225.213.0 - - [25/May/2023 08:16:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug:106.225.213.0 - - [25/May/2023 08:16:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:106.225.155.68 - - [25/May/2023 08:17:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:106.225.155.68 - - [25/May/2023 08:17:09] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:175.6.112.104 - - [25/May/2023 08:17:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.112.104 - - [25/May/2023 08:17:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:175.6.138.11 - - [25/May/2023 08:17:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:175.6.138.11 - - [25/May/2023 08:17:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
remote: Resolving deltas:   0% (0/5)        remote: Resolving deltas:  20% (1/5)        remote: Resolving deltas:  40% (2/5)        remote: Resolving deltas:  60% (3/5)        remote: Resolving deltas:  80% (4/5)        remote: Resolving deltas: 100% (5/5)        remote: Resolving deltas: 100% (5/5), completed with 3 local objects.        
remote: Resolving deltas:   0% (0/7)        remote: Resolving deltas:  14% (1/7)        remote: Resolving deltas:  28% (2/7)        remote: Resolving deltas:  42% (3/7)        remote: Resolving deltas:  57% (4/7)        remote: Resolving deltas:  71% (5/7)        remote: Resolving deltas:  85% (6/7)        remote: Resolving deltas: 100% (7/7)        remote: Resolving deltas: 100% (7/7), completed with 3 local objects.        
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 4e5d9ba881d443bf429d9364943cd3acd036e334 but expected b76aa56e6613b82b45f919b307ef87a054c7af74)
error: 推送一些引用到 'git@github.com:ashen-23/ashen_boring.git' 失败
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-25 14:18:49 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   b76aa56..4e5d9ba  main -> main
ERROR:apscheduler.executors.default:Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-05-25 14:18:48 CST)" raised an exception
Traceback (most recent call last):
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/Apps/ashen_boring/venv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO:werkzeug:47.92.67.105 - - [25/May/2023 12:15:10] "GET http://i.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:8.142.31.72 - - [25/May/2023 12:15:10] "GET http://i.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.73.109 - - [25/May/2023 12:15:10] "[33mGET http://i.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.37.1 - - [25/May/2023 12:24:33] "GET http://docker.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.78.102 - - [25/May/2023 12:24:34] "GET http://docker.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.78.77 - - [25/May/2023 12:24:34] "[33mGET http://docker.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.5.239 - - [25/May/2023 12:25:46] "GET http://qb.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.72.15 - - [25/May/2023 12:25:47] "GET http://qb.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.33.204 - - [25/May/2023 12:25:47] "[33mGET http://qb.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.72.15 - - [25/May/2023 12:30:34] "GET http://iostools.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.79.156 - - [25/May/2023 12:30:34] "GET http://iostools.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.30.57 - - [25/May/2023 12:30:34] "[33mGET http://iostools.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.73.218 - - [25/May/2023 12:32:06] "GET http://tool.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.30.57 - - [25/May/2023 12:32:07] "GET http://tool.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.67.105 - - [25/May/2023 12:32:08] "[33mGET http://tool.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:8.142.87.162 - - [25/May/2023 12:32:21] "GET http://nas.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.72.15 - - [25/May/2023 12:32:22] "GET http://nas.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.70.66 - - [25/May/2023 12:32:22] "[33mGET http://nas.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.78.77 - - [25/May/2023 12:32:29] "GET http://proxy.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.72.15 - - [25/May/2023 12:32:30] "GET http://proxy.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.5.239 - - [25/May/2023 12:32:30] "[33mGET http://proxy.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.68.55 - - [25/May/2023 12:33:04] "GET http://doc.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.30.57 - - [25/May/2023 12:33:04] "GET http://doc.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.70.66 - - [25/May/2023 12:33:04] "[33mGET http://doc.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:8.142.87.162 - - [25/May/2023 12:33:36] "GET http://gelly.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.31.57 - - [25/May/2023 12:33:36] "GET http://gelly.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.29.136 - - [25/May/2023 12:33:36] "[33mGET http://gelly.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.33.185 - - [25/May/2023 12:35:20] "GET http://ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.36.178 - - [25/May/2023 12:35:20] "GET http://ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.79.71 - - [25/May/2023 12:35:20] "[33mGET http://ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.32.64 - - [25/May/2023 12:41:42] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.77.114 - - [25/May/2023 12:41:42] "GET http://39.100.66.203/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.77.114 - - [25/May/2023 12:41:42] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:47.92.79.71 - - [25/May/2023 12:42:04] "GET http://jp.ashen23.site:8801/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.30.214 - - [25/May/2023 12:42:04] "GET http://jp.ashen23.site/ HTTP/1.1" 200 -
INFO:werkzeug:47.92.33.204 - - [25/May/2023 12:42:04] "[33mGET http://jp.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
